# CircleCI 2.0 configuration file
#
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "8.3.3"

    environment:
      BUILD_OS: osx
      TRAVIS_OS_NAME: osx
      CIRCLECI: true

    steps:
      - checkout

      - run:
          name: Before Build
          command: ./build/before_build.sh

      - run:
          name: Build
          command: ./build/build.sh
